version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - db

    web:
        image: nginx:latest
        container_name: nginx_server
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: sozitoban
            MYSQL_ROOT_PASSWORD: tatsutora88 # ✅ "tatsutora88" に変更
            MYSQL_PASSWORD: tatsutora88 # ✅ "tatsutora88" に統一
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:


volumes:
    db_data:
